In [11]:
#1+
import random
a=[random.randint(1, 10) for i in range(10)]
print(a)
n=int(input('Введите число: '))
def f(a,n):
    b=[]
    for i in a:
        if i%n==0:
            b.append(i)
    return b
print(f(a,n))

[4, 4, 1, 8, 10, 5, 6, 1, 9, 2]
Введите число: 2
[4, 4, 8, 10, 6, 2]

In [118]:
#2
import random
a=[random.randint(1, 10) for i in range(10)]
print(a)
def f(a):
    b=[]
    for i in range(len(a)):
        if (i+1) %5 == 0:
            b.append(a[i]*2)
        if (i+1) %3 != 0:
            b.append(a[i])        
    return b
print(f(a))

[6, 10, 2, 7, 10, 8, 3, 9, 3, 2]
[6, 10, 7, 20, 10, 3, 9, 4, 2]

In [41]:
#3+
import random
a=[random.randint(1, 10) for i in range(10)]
print(a)
n=int(input('Введите число: '))
def f(a,n):
    sum=0
    for i in a:
        if i==n:
            sum+=1
    return sum
print(f(a,n))

[4, 1, 6, 2, 2, 6, 10, 5, 2, 9]
Введите число: 2
3

In [82]:
#4+
import random
a=[random.randint(1, 10) for i in range(9)]
print(a)
def f(c):
    b=[]
    i = 0
    for j in range(int(len(c)/3)):
        a=c[i:i+3]
        b.extend(a[::-1])
        i+=len(a)
    return b
print(f(a))

[3, 2, 8, 2, 5, 6, 4, 3, 3]
[8, 2, 3, 6, 5, 2, 3, 3, 4]

In [49]:
#5+
import random
a=[random.randint(1, 10) for i in range(10)]
b=[random.randint(1, 10) for i in range(10)]
print(a)
print(b)
def f(a,b):
    c=[]
    for i in range(len(a)):
        c.append(a[i]-b[i])
    return c
print(f(a,b))

[8, 8, 7, 3, 1, 9, 1, 2, 4, 5]
[4, 8, 9, 4, 7, 9, 9, 9, 3, 2]
[4, 0, -2, -1, -6, 0, -8, -7, 1, 3]

In [99]:
#6+
import random
a = [random.randint(1, 10) for i in range(10)]
print(a)
def f(a):
    b=[]
    works=[]
    for i in a:
        if i in works:
            continue
        b.append(a.count(i))
        works.append(i)
    return b
print(f(a))

[1, 8, 8, 9, 6, 3, 1, 8, 4, 1]
[3, 3, 1, 1, 1, 1]

In [92]:
#7+
import random
a=[random.randint(-10, 10) for i in range(10)]
print(a)
def f(a):
    return sorted([i for i in a if i > 0])
print(f(a))

[-7, 6, -10, 8, 4, 7, -6, -7, 9, -2]
[4, 6, 7, 8, 9]

In [114]:
#8+
n=int(input('Введите число: '))
a=list(range(0,n-2))
print('Исходный список:', a)
def f(n,a):
    b = list()
    for i in range(0, n):
        if i not in a:
            b.append(i)
    return b
print(f(n,a))

Введите число: 4
Исходный список: [0, 1]
[2, 3]

In [1]:
#2.1
import numpy as np
import pandas as pd

data=pd.read_csv("https://raw.githubusercontent.com/junaart/ForStudents/master/Big_Data/Seminar_4/data_1.csv")
display(data)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
...,...,...,...,...,...,...,...
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [2]:
data_male = data[data['Пол']=='м']
data_female = data[data['Пол']=='ж']
display(data_male)
display(data_female)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0
6,Ахундов О.Т.,01.05.1967,м,23.05.1986,4400,холост,NaN
8,Белорусец И.А.,04.11.1960,м,09.03.1989,4000,холост,NaN
10,Булгаков Ю.В.,01.05.1957,м,09.06.1985,3000,женат,1.0
13,Варлаков В.Н.,23.10.1966,м,12.09.1995,5000,холост,NaN
18,Гостев И.И.,22.11.1969,м,13.09.1996,6000,женат,2.0
20,Гринченко М.В.,08.12.1954,м,06.09.1985,4300,женат,1.0
25,Ежиков А.В.,14.02.1963,м,01.11.1990,6000,женат,4.0
27,Зайцев Б.П.,20.08.1959,м,05.10.1995,5000,женат,1.0
31,Кирюхин В.Н.,20.08.1954,м,09.12.1985,4900,женат,2.0
34,Колесников И.С.,25.03.1964,м,05.03.1985,6000,холост,NaN
41,Леонтьев В.К.,06.01.1979,м,11.08.1990,2700,холост,NaN
42,Локшин Я.С.,17.01.1961,м,06.09.1985,5000,женат,1.0
43,Львов Г.Н.,13.07.1947,м,09.12.1990,3000,женат,3.0
44,Малахов Г.И.,08.12.1954,м,06.09.1985,4300,женат,1.0
45,Марченко А.Н.,03.10.1936,м,04.08.1980,7000,женат,NaN
46,Медведев Б.М.,24.04.1960,м,04.05.1994,5600,женат,3.0
47,Мельников А.С.,11.07.1961,м,21.03.1986,5400,разведен,1.0
48,Минаев Ю.В.,08.08.1956,м,09.12.1987,3000,холост,NaN
51,Муленков Е.И.,09.11.1969,м,20.12.1992,4300,холост,1.0
55,Овчинников А.М.,09.11.1969,м,20.12.1992,4300,женат,1.0
59,Полибин А.А.,05.05.1967,м,04.05.1984,4400,женат,NaN
61,Реутенко Р.В.,06.11.1978,м,20.12.1992,4700,холост,NaN
65,Рыбальский Г.Л.,12.10.1958,м,23.05.1995,5600,женат,2.0
66,Рыжов А.В.,12.10.1958,м,23.05.1995,5600,женат,2.0
67,Сарайкин В.Ф.,05.06.1965,м,12.06.1985,4900,женат,1.0
68,Сафронов В.В.,06.04.1979,м,08.10.1998,2400,холост,NaN
69,Семенов М.П.,09.01.1970,м,11.08.1990,4700,женат,NaN
70,Скворцов С.М.,06.04.1979,м,08.10.1998,3800,холост,NaN
74,Страшнов Г.Г.,06.02.1954,м,23.05.1995,4500,женат,1.0
75,Сулдин В.Г.,11.03.1979,м,08.10.1998,3500,холост,NaN
76,Сыроватский И.В.,25.04.1977,м,23.11.1998,4400,женат,1.0
80,Устинов А.А.,31.03.1934,м,09.06.1985,4700,разведен,NaN
82,Ушкаров Н.А.,13.11.1979,м,23.11.2001,4000,холост,NaN
83,Федоров Д.М.,31.03.1932,м,09.06.1975,7700,женат,2.0
86,Фетисов А.Н.,11.12.1948,м,23.05.1986,4000,женат,1.0
92,Чернов Е.В.,15.05.1972,м,06.09.2001,5500,женат,1.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
5,Афоничева Л.В.,08.06.1978,ж,22.09.1998,3000,замужем,NaN
7,Бегунова С.А.,20.05.1973,ж,11.09.1997,4400,замужем,1.0
9,Бизюкова Г.П.,01.05.1957,ж,09.06.1985,4000,замужем,1.0
11,Быкова И.А.,12.01.1958,ж,25.07.1994,5600,замужем,2.0
12,Вантеева Л.В.,12.01.1958,ж,25.07.1994,4500,замужем,2.0
14,Васильева Е.Г.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
15,Вуколова О.В.,14.02.1963,ж,01.11.1990,3500,замужем,2.0
16,Гаранина Г.П.,05.06.1965,ж,12.06.1985,3500,замужем,1.0
17,Гордеева Н.А.,16.11.1953,ж,05.03.1985,4100,замужем,NaN
19,Грачева О.Е.,13.05.1967,ж,14.09.2000,4500,замужем,NaN
21,Гусева И.А.,06.06.1956,ж,09.12.1987,4900,разведена,1.0
22,Дзебоева Н.А.,20.08.1954,ж,09.12.1985,4600,замужем,2.0
23,Дмитриева З.Е.,22.09.1980,ж,09.05.1998,4700,незамужем,NaN
24,Дробикова С.А.,11.07.1961,ж,21.03.1986,5600,замужем,1.0
26,Ермолаева Е.И.,01.05.1967,ж,23.05.1986,4300,незамужем,NaN
28,Зайцева Т.Н.,22.09.1980,ж,09.05.1998,3800,незамужем,NaN
29,Захарова В.В.,24.06.1964,ж,15.09.1995,4300,замужем,2.0
30,Истратова Е.Н.,25.03.1964,ж,05.03.1985,3000,замужем,2.0
32,Ковалева М.Г.,20.08.1959,ж,05.10.1995,4500,замужем,1.0
33,Колганова В.В.,07.08.1951,ж,04.08.1980,4450,замужем,1.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0
36,Корчагина О.С.,05.05.1967,ж,04.05.1984,4400,замужем,1.0
37,Курдина С.Х.,16.11.1953,ж,05.03.1985,4100,замужем,NaN
38,Лазькова Л.В.,06.11.1978,ж,20.12.1992,4700,незамужем,NaN
39,Ларшина Н.П.,06.12.1978,ж,08.08.1997,4000,незамужем,1.0
40,Леонова Е.И.,13.07.1947,ж,09.12.1990,3000,замужем,3.0
49,Михайлова Т.В.,06.02.1954,ж,23.05.1995,3000,замужем,3.0
50,Моисеева В.Б.,07.08.1962,ж,04.09.1980,4450,замужем,2.0
52,Муравьева В.С.,03.10.1955,ж,04.08.1980,3000,незамужем,NaN
53,Нарольская Т.С.,14.05.1962,ж,04.05.1994,4000,замужем,2.0
54,Носова Л.Г.,15.07.1974,ж,08.08.1997,4300,незамужем,NaN
56,Петухова Т.Н.,06.03.1979,ж,08.10.1998,3500,незамужем,NaN
57,Пименова О.Н.,01.09.1957,ж,11.08.1990,5600,замужем,3.0
58,Позднякова Т.И.,15.07.1974,ж,08.08.1997,4300,разведена,NaN
60,Пономарева Л.А.,04.09.1945,ж,21.03.1986,4000,замужем,3.0
62,Родникова С.В.,01.09.1957,ж,11.08.1990,5600,замужем,1.0
63,Романова А.И.,12.12.1977,ж,08.08.1997,4000,незамужем,1.0
64,Романова З.В.,06.04.1974,ж,23.11.1998,4600,замужем,1.0
71,Смирнова И.В.,02.01.1948,ж,23.11.1985,5600,замужем,2.0
72,Соколова А.В.,02.01.1948,ж,23.11.1985,5600,разведена,2.0
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0
77,Туровская Н.С.,08.05.1979,ж,05.09.1997,5600,незамужем,NaN
78,Тяпкина Л.А.,06.06.1952,ж,08.10.1980,4000,замужем,NaN
79,Укладчикова Н.И.,16.12.1976,ж,05.09.1997,3700,незамужем,NaN
81,Ушакова И.И.,06.05.1979,ж,05.09.1997,5600,незамужем,NaN
84,Федорова З.А.,02.04.1952,ж,23.09.1992,4600,замужем,NaN
85,Федюшкина М.А.,02.04.1950,ж,25.07.1994,4600,замужем,1.0
87,Филатова О.В.,21.01.1942,ж,01.11.1980,4600,замужем,NaN
88,Харькова Л.В.,23.08.1980,ж,05.09.1997,4500,незамужем,NaN
89,Хромова Л.В.,21.01.1937,ж,01.11.1980,4600,замужем,NaN
90,Хромова Л.В.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
91,Червякова Н.С.,06.06.1946,ж,08.10.1980,4000,замужем,NaN
93,Чигрина А.Е.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
94,Чиркина А.М.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [11]:
import datetime as dt

dataM = data[data['Пол']=='м']
dataM['Дата приема на работу'] = pd.to_datetime(dataM['Дата приема на работу'])

dataM.loc[:, 'Стаж'] = (np.floor((pd.to_datetime(dt.date.today().strftime('%Y-%m-%d')) - dataM['Дата приема на работу']).dt.days / 365.25)).astype(int)
dataM

C:\Users\nikit\AppData\Local\Temp/ipykernel_1920/3916667104.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataM['Дата приема на работу'] = pd.to_datetime(dataM['Дата приема на работу'])
C:\Users\nikit\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Стаж
0,Алистратов А.А.,27.10.1975,м,1997-08-09,4000,женат,1.0,24
1,Анохин Н.И.,11.12.1948,м,1986-05-23,5000,разведен,1.0,35
6,Ахундов О.Т.,01.05.1967,м,1986-05-23,4400,холост,NaN,35
8,Белорусец И.А.,04.11.1960,м,1989-09-03,4000,холост,NaN,32
10,Булгаков Ю.В.,01.05.1957,м,1985-09-06,3000,женат,1.0,36
13,Варлаков В.Н.,23.10.1966,м,1995-12-09,5000,холост,NaN,25
18,Гостев И.И.,22.11.1969,м,1996-09-13,6000,женат,2.0,25
20,Гринченко М.В.,08.12.1954,м,1985-06-09,4300,женат,1.0,36
25,Ежиков А.В.,14.02.1963,м,1990-01-11,6000,женат,4.0,31
27,Зайцев Б.П.,20.08.1959,м,1995-05-10,5000,женат,1.0,26
31,Кирюхин В.Н.,20.08.1954,м,1985-09-12,4900,женат,2.0,36
34,Колесников И.С.,25.03.1964,м,1985-05-03,6000,холост,NaN,36
41,Леонтьев В.К.,06.01.1979,м,1990-11-08,2700,холост,NaN,30
42,Локшин Я.С.,17.01.1961,м,1985-06-09,5000,женат,1.0,36
43,Львов Г.Н.,13.07.1947,м,1990-09-12,3000,женат,3.0,31
44,Малахов Г.И.,08.12.1954,м,1985-06-09,4300,женат,1.0,36
45,Марченко А.Н.,03.10.1936,м,1980-04-08,7000,женат,NaN,41
46,Медведев Б.М.,24.04.1960,м,1994-04-05,5600,женат,3.0,27
47,Мельников А.С.,11.07.1961,м,1986-03-21,5400,разведен,1.0,35
48,Минаев Ю.В.,08.08.1956,м,1987-09-12,3000,холост,NaN,34
51,Муленков Е.И.,09.11.1969,м,1992-12-20,4300,холост,1.0,28
55,Овчинников А.М.,09.11.1969,м,1992-12-20,4300,женат,1.0,28
59,Полибин А.А.,05.05.1967,м,1984-04-05,4400,женат,NaN,37
61,Реутенко Р.В.,06.11.1978,м,1992-12-20,4700,холост,NaN,28
65,Рыбальский Г.Л.,12.10.1958,м,1995-05-23,5600,женат,2.0,26
66,Рыжов А.В.,12.10.1958,м,1995-05-23,5600,женат,2.0,26
67,Сарайкин В.Ф.,05.06.1965,м,1985-12-06,4900,женат,1.0,35
68,Сафронов В.В.,06.04.1979,м,1998-08-10,2400,холост,NaN,23
69,Семенов М.П.,09.01.1970,м,1990-11-08,4700,женат,NaN,30
70,Скворцов С.М.,06.04.1979,м,1998-08-10,3800,холост,NaN,23
74,Страшнов Г.Г.,06.02.1954,м,1995-05-23,4500,женат,1.0,26
75,Сулдин В.Г.,11.03.1979,м,1998-08-10,3500,холост,NaN,23
76,Сыроватский И.В.,25.04.1977,м,1998-11-23,4400,женат,1.0,22
80,Устинов А.А.,31.03.1934,м,1985-09-06,4700,разведен,NaN,36
82,Ушкаров Н.А.,13.11.1979,м,2001-11-23,4000,холост,NaN,19
83,Федоров Д.М.,31.03.1932,м,1975-09-06,7700,женат,2.0,46
86,Фетисов А.Н.,11.12.1948,м,1986-05-23,4000,женат,1.0,35
92,Чернов Е.В.,15.05.1972,м,2001-06-09,5500,женат,1.0,20
96,Шиманюк Н.И.,06.11.1979,м,1998-11-23,4000,холост,NaN,22
97,Элиава Т.М.,19.05.1981,м,1997-10-09,3700,холост,NaN,23

In [12]:
dataZH = data[data['Пол']=='ж']
dataZH['Дата рождения'] = pd.to_datetime(dataZH['Дата рождения'])

dataZH.loc[:, 'Возраст'] = (np.floor((pd.to_datetime(dt.date.today().strftime('%Y-%m-%d')) - dataZH['Дата рождения']).dt.days / 365.25)).astype(int)
dataZH

C:\Users\nikit\AppData\Local\Temp/ipykernel_1920/3527616092.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataZH['Дата рождения'] = pd.to_datetime(dataZH['Дата рождения'])
C:\Users\nikit\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Возраст
2,Антонова И.П.,1951-04-12,ж,09.05.1988,4300,замужем,1.0,70
3,Артемова Г.А.,1979-06-08,ж,05.09.1997,4500,незамужем,NaN,42
4,Афоничева Л.К.,1952-09-01,ж,05.10.1985,4900,замужем,1.0,69
5,Афоничева Л.В.,1978-08-06,ж,22.09.1998,3000,замужем,NaN,43
7,Бегунова С.А.,1973-05-20,ж,11.09.1997,4400,замужем,1.0,48
9,Бизюкова Г.П.,1957-01-05,ж,09.06.1985,4000,замужем,1.0,64
11,Быкова И.А.,1958-12-01,ж,25.07.1994,5600,замужем,2.0,62
12,Вантеева Л.В.,1958-12-01,ж,25.07.1994,4500,замужем,2.0,62
14,Васильева Е.Г.,1952-09-01,ж,05.10.1985,4900,замужем,1.0,69
15,Вуколова О.В.,1963-02-14,ж,01.11.1990,3500,замужем,2.0,58
16,Гаранина Г.П.,1965-05-06,ж,12.06.1985,3500,замужем,1.0,56
17,Гордеева Н.А.,1953-11-16,ж,05.03.1985,4100,замужем,NaN,67
19,Грачева О.Е.,1967-05-13,ж,14.09.2000,4500,замужем,NaN,54
21,Гусева И.А.,1956-06-06,ж,09.12.1987,4900,разведена,1.0,65
22,Дзебоева Н.А.,1954-08-20,ж,09.12.1985,4600,замужем,2.0,67
23,Дмитриева З.Е.,1980-09-22,ж,09.05.1998,4700,незамужем,NaN,41
24,Дробикова С.А.,1961-11-07,ж,21.03.1986,5600,замужем,1.0,59
26,Ермолаева Е.И.,1967-01-05,ж,23.05.1986,4300,незамужем,NaN,54
28,Зайцева Т.Н.,1980-09-22,ж,09.05.1998,3800,незамужем,NaN,41
29,Захарова В.В.,1964-06-24,ж,15.09.1995,4300,замужем,2.0,57
30,Истратова Е.Н.,1964-03-25,ж,05.03.1985,3000,замужем,2.0,57
32,Ковалева М.Г.,1959-08-20,ж,05.10.1995,4500,замужем,1.0,62
33,Колганова В.В.,1951-07-08,ж,04.08.1980,4450,замужем,1.0,70
35,Конюхова Л.Н.,1951-01-17,ж,06.09.1985,3000,разведена,1.0,70
36,Корчагина О.С.,1967-05-05,ж,04.05.1984,4400,замужем,1.0,54
37,Курдина С.Х.,1953-11-16,ж,05.03.1985,4100,замужем,NaN,67
38,Лазькова Л.В.,1978-06-11,ж,20.12.1992,4700,незамужем,NaN,43
39,Ларшина Н.П.,1978-06-12,ж,08.08.1997,4000,незамужем,1.0,43
40,Леонова Е.И.,1947-07-13,ж,09.12.1990,3000,замужем,3.0,74
49,Михайлова Т.В.,1954-06-02,ж,23.05.1995,3000,замужем,3.0,67
50,Моисеева В.Б.,1962-07-08,ж,04.09.1980,4450,замужем,2.0,59
52,Муравьева В.С.,1955-03-10,ж,04.08.1980,3000,незамужем,NaN,66
53,Нарольская Т.С.,1962-05-14,ж,04.05.1994,4000,замужем,2.0,59
54,Носова Л.Г.,1974-07-15,ж,08.08.1997,4300,незамужем,NaN,47
56,Петухова Т.Н.,1979-06-03,ж,08.10.1998,3500,незамужем,NaN,42
57,Пименова О.Н.,1957-01-09,ж,11.08.1990,5600,замужем,3.0,64
58,Позднякова Т.И.,1974-07-15,ж,08.08.1997,4300,разведена,NaN,47
60,Пономарева Л.А.,1945-04-09,ж,21.03.1986,4000,замужем,3.0,76
62,Родникова С.В.,1957-01-09,ж,11.08.1990,5600,замужем,1.0,64
63,Романова А.И.,1977-12-12,ж,08.08.1997,4000,незамужем,1.0,43
64,Романова З.В.,1974-06-04,ж,23.11.1998,4600,замужем,1.0,47
71,Смирнова И.В.,1948-02-01,ж,23.11.1985,5600,замужем,2.0,73
72,Соколова А.В.,1948-02-01,ж,23.11.1985,5600,разведена,2.0,73
73,Степина Т.И.,1976-12-16,ж,05.09.1997,3700,замужем,1.0,44
77,Туровская Н.С.,1979-08-05,ж,05.09.1997,5600,незамужем,NaN,42
78,Тяпкина Л.А.,1952-06-06,ж,08.10.1980,4000,замужем,NaN,69
79,Укладчикова Н.И.,1976-12-16,ж,05.09.1997,3700,незамужем,NaN,44
81,Ушакова И.И.,1979-06-05,ж,05.09.1997,5600,незамужем,NaN,42
84,Федорова З.А.,1952-02-04,ж,23.09.1992,4600,замужем,NaN,69
85,Федюшкина М.А.,1950-02-04,ж,25.07.1994,4600,замужем,1.0,71
87,Филатова О.В.,1942-01-21,ж,01.11.1980,4600,замужем,NaN,79
88,Харькова Л.В.,1980-08-23,ж,05.09.1997,4500,незамужем,NaN,41
89,Хромова Л.В.,1937-01-21,ж,01.11.1980,4600,замужем,NaN,84
90,Хромова Л.В.,1938-07-08,ж,12.06.1985,3000,замужем,1.0,83
91,Червякова Н.С.,1946-06-06,ж,08.10.1980,4000,замужем,NaN,75
93,Чигрина А.Е.,1939-07-29,ж,09.12.1985,4500,замужем,1.0,82
94,Чиркина А.М.,1938-07-08,ж,12.06.1985,3000,замужем,1.0,83
95,Шафеева Н.К.,1939-07-29,ж,09.12.1985,4500,замужем,1.0,82
98,Якимова Н.М.,1973-05-16,ж,07.09.1999,3000,замужем,2.0,48
99,Яфарова Т.Н.,1945-04-09,ж,21.03.1986,4000,замужем,2.0,76

In [6]:
data[(data['Кол-во детей']>0) & (data['Оклад']<data['Оклад'].mean())]

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
7,Бегунова С.А.,20.05.1973,ж,11.09.1997,4400,замужем,1.0
9,Бизюкова Г.П.,01.05.1957,ж,09.06.1985,4000,замужем,1.0
10,Булгаков Ю.В.,01.05.1957,м,09.06.1985,3000,женат,1.0
15,Вуколова О.В.,14.02.1963,ж,01.11.1990,3500,замужем,2.0
16,Гаранина Г.П.,05.06.1965,ж,12.06.1985,3500,замужем,1.0
20,Гринченко М.В.,08.12.1954,м,06.09.1985,4300,женат,1.0
29,Захарова В.В.,24.06.1964,ж,15.09.1995,4300,замужем,2.0
30,Истратова Е.Н.,25.03.1964,ж,05.03.1985,3000,замужем,2.0
35,Конюхова Л.Н.,17.01.1951,ж,06.09.1985,3000,разведена,1.0
36,Корчагина О.С.,05.05.1967,ж,04.05.1984,4400,замужем,1.0
39,Ларшина Н.П.,06.12.1978,ж,08.08.1997,4000,незамужем,1.0
40,Леонова Е.И.,13.07.1947,ж,09.12.1990,3000,замужем,3.0
43,Львов Г.Н.,13.07.1947,м,09.12.1990,3000,женат,3.0
44,Малахов Г.И.,08.12.1954,м,06.09.1985,4300,женат,1.0
49,Михайлова Т.В.,06.02.1954,ж,23.05.1995,3000,замужем,3.0
51,Муленков Е.И.,09.11.1969,м,20.12.1992,4300,холост,1.0
53,Нарольская Т.С.,14.05.1962,ж,04.05.1994,4000,замужем,2.0
55,Овчинников А.М.,09.11.1969,м,20.12.1992,4300,женат,1.0
60,Пономарева Л.А.,04.09.1945,ж,21.03.1986,4000,замужем,3.0
63,Романова А.И.,12.12.1977,ж,08.08.1997,4000,незамужем,1.0
73,Степина Т.И.,16.12.1976,ж,05.09.1997,3700,замужем,1.0
76,Сыроватский И.В.,25.04.1977,м,23.11.1998,4400,женат,1.0
86,Фетисов А.Н.,11.12.1948,м,23.05.1986,4000,женат,1.0
90,Хромова Л.В.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
94,Чиркина А.М.,07.08.1938,ж,12.06.1985,3000,замужем,1.0
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [25]:
data['Дата рождения'] = pd.to_datetime(data['Дата рождения'])

data['Возраст'] = np.floor((pd.to_datetime(dt.date.today().strftime('%Y-%m-%d')) - data['Дата рождения']).dt.days / 365.25).astype('int', errors='ignore')
data[(data['Возраст'] % 5) == 0]

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Возраст
0,Алистратов А.А.,1975-10-27,м,08.09.1997,4000,женат,1.0,45
2,Антонова И.П.,1951-04-12,ж,09.05.1988,4300,замужем,1.0,70
21,Гусева И.А.,1956-06-06,ж,09.12.1987,4900,разведена,1.0,65
33,Колганова В.В.,1951-07-08,ж,04.08.1980,4450,замужем,1.0,70
35,Конюхова Л.Н.,1951-01-17,ж,06.09.1985,3000,разведена,1.0,70
42,Локшин Я.С.,1961-01-17,м,06.09.1985,5000,женат,1.0,60
45,Марченко А.Н.,1936-03-10,м,04.08.1980,7000,женат,NaN,85
48,Минаев Ю.В.,1956-08-08,м,09.12.1987,3000,холост,NaN,65
91,Червякова Н.С.,1946-06-06,ж,08.10.1980,4000,замужем,NaN,75
97,Элиава Т.М.,1981-05-19,м,10.09.1997,3700,холост,NaN,40

In [23]:
new_data = pd.DataFrame(columns = ['Женат','Замужем','Холост','Незамужем','Разведен','Разведена'])
new_data.loc[0, 'Женат'] = data[data['Семейное положение'] == 'женат']['Семейное положение'].count()
new_data.loc[0, 'Замужем'] = data[data['Семейное положение'] == 'замужем']['Семейное положение'].count()
new_data.loc[0, 'Холост'] = data[data['Семейное положение'] == 'холост']['Семейное положение'].count()
new_data.loc[0, 'Незамужем'] = data[data['Семейное положение'] == 'незамужем']['Семейное положение'].count()
new_data.loc[0, 'Разведен'] = data[data['Семейное положение'] == 'разведен']['Семейное положение'].count()
new_data.loc[0, 'Разведена'] = data[data['Семейное положение'] == 'разведена']['Семейное положение'].count()
display(new_data)

  Женат Замужем Холост Незамужем Разведен Разведена
0    23      42     14        14        3         4